version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:11"
      timezone: "America/Chicago"
    labels:
      - ":robot: bot"

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
