group:

  # Webiste ONLY
  - files:
      - source: .git-sync/site/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
        deleteOrphaned: true
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io@dev
      Bearsampp/Bearsampp.github.io@master
      Bearsampp/construction

# Add modules since they share common needs
  - files:
      - source: .git-sync/modules/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
        deleteOrphaned: true
    repos: |
      Bearsampp/Bearsampp
      Bearsampp/module-apache
      Bearsampp/module-adminer
      Bearsampp/module-filezilla
