group:
  - files:
      - source: .git-sync/site/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
        deleteOrphaned: true
        BRANCH_PREFIX: dev
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io

  - files:
      - source: .git-sync/modules/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
        deleteOrphaned: true
    repos: |
      Bearsampp/module-apache
      Bearsampp/module-adminer
      Bearsampp/module-filezilla

