group:
  # Bearsampp repo unique things
  - files:
      - source: .github/workflows/changelog.yml
        dest: .github/workflows/changelog.yml
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: img/artwork/favicon.ico
        dest: core/homepage/resources/img/icons/favicon.ico
      - source: .common
        dest: .github
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
      - source: LICENSE
        dest: LICENSE
    repos: |
        Bearsampp/Bearsampp

  # Prerequisites unique things
  - files:
      - source: img/artwork/Bearsampp-logo-128x128.ico
        dest:  setup/bearsampp.ico
      - source: img/artwork/bearsampp.bmp
        dest: setup/bearsampp.bmp
      - source: img/artwork/prerequisites.bmp
        dest: setup/prerequisites.bmp
      - source: .gitignore
        dest: .gitignore
    repos: |
      Bearsampp/prerequisites


  # All COMMON items go here
  - files:
      - source: .common
        dest: .github
      - source: .github/.phpstorm-metadata/winbinder.php
        dest: .github/.phpstorm-metadata/winbinder.php
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore.common
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: img/artwork/favicon.ico
        dest: favicon.ico
    repos: |
        Bearsampp/dev
        Bearsampp/aetraymenu
        Bearsampp/module-apache
        Bearsampp/module-bruno
        Bearsampp/module-composer
        Bearsampp/module-cmder
        Bearsampp/module-ghostscript
        Bearsampp/module-git
        Bearsampp/module-mailpit
        Bearsampp/module-mariadb
        Bearsampp/module-memcached
        Bearsampp/module-mysql
        Bearsampp/module-ngrok
        Bearsampp/module-nodejs
        Bearsampp/module-perl
        Bearsampp/module-php
        Bearsampp/module-phpmyadmin
        Bearsampp/module-phppgadmin
        Bearsampp/module-postgresql
        Bearsampp/module-python
        Bearsampp/module-ruby
        Bearsampp/module-xlight
        Bearsampp/modules-untouched
        Bearsampp/prerequisites
        Bearsampp/.teams


  # All SANDBOX items go here
  - files:
      - source: .common
        dest: .github
      - source: .github/.phpstorm-metadata/winbinder.php
        dest: .github/.phpstorm-metadata/winbinder.php
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
      - source: LICENSE
        dest: LICENSE
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: img/artwork/favicon.ico
        dest: favicon.ico
    repos: |
        Bearsampp/sandbox

  # Things for modules ONLY!
  - files:
      - source: .dispatcher
        dest: .github/workflows
      - source: .releases/update-releases-properties.yml
        dest: .github/workflows/update-releases-properties.yml
      - source: .releases/validate-properties-links.yml
        dest: .github/workflows/validate-properties-links.yml
    repos: |
        Bearsampp/module-apache
        Bearsampp/module-bruno
        Bearsampp/module-cmder
        Bearsampp/module-composer
        Bearsampp/module-ghostscript
        Bearsampp/module-git
        Bearsampp/module-mailpit
        Bearsampp/module-mariadb
        Bearsampp/module-memcached
        Bearsampp/module-mysql
        Bearsampp/module-ngrok
        Bearsampp/module-nodejs
        Bearsampp/module-perl
        Bearsampp/module-php
        Bearsampp/module-phpmyadmin
        Bearsampp/module-phppgadmin
        Bearsampp/module-postgresql
        Bearsampp/module-python
        Bearsampp/module-ruby
        Bearsampp/module-xlight

  # Things for modules-untouched ONLY!
  - files:
      - source: .releases/update-module-properties.yml
        dest: .github/workflows/update-module-properties.yml
      - source: .releases/validate-properties-links.yml
        dest: .github/workflows/validate-properties-links.yml
    repos: |
        Bearsampp/modules-untouched
