group:

  # Add modules since they share common needs
  - files:
      - source: .git-sync/modules/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: img/Bearsampp-logo-500x-500x-transparent.png
        dest: img/Bearsampp-logo.png
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
    repos: |
        Bearsampp/Bearsampp

  - files:
      - source: img/Bearsampp-logo-500x-500x-transparent.png
        dest: img/Bearsampp-logo.png
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: .git-sync/modules/.github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .git-sync/modules/.github/FUNDING.yml
        dest: .github/FUNDING.yml
    repos: |
        Bearsampp/dev
        Bearsampp/login-servers-enhanced
        Bearsampp/module-adminer
        Bearsampp/module-apache
        Bearsampp/module-composer
        Bearsampp/module-consolez
        Bearsampp/module-filezilla
        Bearsampp/module-ghostscript
        Bearsampp/module-git
        Bearsampp/module-gitlist
        Bearsampp/module-mailhog
        Bearsampp/module-mariadb
        Bearsampp/module-memcached
        Bearsampp/module-mysql
        Bearsampp/module-ngrok
        Bearsampp/module-nodejs
        Bearsampp/module-perl
        Bearsampp/module-phpmemadmin
        Bearsampp/module-phpmyadmin
        Bearsampp/module-phppgadmin
        Bearsampp/module-postgresql
        Bearsampp/module-python
        Bearsampp/module-ruby
        Bearsampp/module-svn
        Bearsampp/module-webgrind
        Bearsampp/module-websvn
        Bearsampp/module-xdc
        Bearsampp/module-yarn
        Bearsampp/modules-untouched
        Bearsampp/prerequisites
