group:

  # Webiste ONLY
  - files:
      - source: .git-sync/site/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: LICENSE
      - source: .gitignore
      - source: .editorconfig
      - source: img
        deleteOrphaned: true
      - source: /favicon.ico
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io@dev
      Bearsampp/Bearsampp.github.io@master

  # Construction ONLY
  - files:
    - source: img
      dest: img
      deleteOrphaned: true
    - source: /favicon.ico
    - source: .git-sync/construction/img
      dest: img
      deleteOrphaned: true
    repos: |
      Bearsampp/construction

# Add modules since they share common needs
  - files:
      - source: .git-sync/modules/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: LICENSE
      - source: .gitignore
      - source: .editorconfig
      - source: img
        deleteOrphaned: true
    repos: |
      Bearsampp/Bearsampp
      Bearsampp/module-apache
      Bearsampp/module-adminer
      Bearsampp/module-filezilla
