group:

  # Bearsampp repo unique things
  - files:
      - source: img/artwork/bearsampp.bmp
        dest: core/resources/homepage/img/bearsampp.bmp
      - source: img/artwork/Bearsampp-logo-128x128.ico
        dest: core/resources/homepage/img/icons/app.ico
      - source: img/artwork/about.bmp
        dest: core/resources/homepage/img/about.bmp
      - source: .github/workflows/changelog.yml
        dest: .github/workflows/changelog.yml
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: img/artwork/favicon.ico
        dest: core/homepage/resources/img/icons/favicon.ico
      - source: .common
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
    repos: |
        Bearsampp/Bearsampp

  # Prerequisites unique things
  - files:
      - source: img/artwork/Bearsampp-logo-128x128.ico
        dest:  setup/bearsampp.ico
      - source: img/artwork/bearsampp.bmp
        dest: setup/bearsampp.bmp
      - source: img/artwork/prerequisites.bmp
        dest: setup/prerequisites.bmp
      - source: .gitignore
        dest: .gitignore
    repos: |
      Bearsampp/prerequisites


  # All COMMON items go here
  - files:
      - source: .common
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore.common
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: img/artwork/favicon.ico
        dest: favicon.ico
    repos: |
        Bearsampp/dev
        Bearsampp/login-servers-enhanced
        Bearsampp/aetraymenu
        Bearsampp/module-adminer
        Bearsampp/module-apache
        Bearsampp/module-composer
        Bearsampp/module-consolez
        Bearsampp/module-ghostscript
        Bearsampp/module-git
        Bearsampp/module-mailpit
        Bearsampp/module-mariadb
        Bearsampp/module-memcached
        Bearsampp/module-mysql
        Bearsampp/module-ngrok
        Bearsampp/module-nodejs
        Bearsampp/module-perl
        Bearsampp/module-php
        Bearsampp/module-phpmyadmin
        Bearsampp/module-phppgadmin
        Bearsampp/module-postgresql
        Bearsampp/module-python
        Bearsampp/module-ruby
        Bearsampp/module-webgrind
        Bearsampp/module-xdc
        Bearsampp/module-xlight
        Bearsampp/module-yarn
        Bearsampp/modules-untouched
        Bearsampp/prerequisites
        Bearsampp/.teams

    # Things for modules ONLY!
  - files:
        - source: .dispatcher
          dest: .github/workflows
          deleteOrphaned: true # Removes deleted files
    repos: |
        Bearsampp/module-adminer
        Bearsampp/module-apache
        Bearsampp/module-composer
        Bearsampp/module-consolez
        Bearsampp/module-ghostscript
        Bearsampp/module-git
        Bearsampp/module-mailpit
        Bearsampp/module-mariadb
        Bearsampp/module-memcached
        Bearsampp/module-mysql
        Bearsampp/module-ngrok
        Bearsampp/module-nodejs
        Bearsampp/module-perl
        Bearsampp/module-php
        Bearsampp/module-phpmyadmin
        Bearsampp/module-phppgadmin
        Bearsampp/module-postgresql
        Bearsampp/module-python
        Bearsampp/module-ruby
        Bearsampp/module-webgrind
        Bearsampp/module-xdc
        Bearsampp/module-xlight
        Bearsampp/module-yarn
