group:

  # Add modules since they share common needs
  - files:
      - source: .git-sync/modules/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
      - source: img/artwork/tool.png
        dest: img/tool.png
      - source: img/artwork/binary.png
        dest: img/binary.png
      - source: img/artwork/application.png
        dest: img/application.png
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: .github/workflows/create-labels.yml
        dest: .github/workflows/create-labels.yml
      - source: .github/labels.yml
        dest: .github/labels.yml
    repos: |
        Bearsampp/Bearsampp

  # Prerequisites unique things
  - files:
      - source: img/artwork/Bearsampp-logo-128x128.ico
        dest:  setup/bearsampp.ico
      - source: img/artwork/Bearsampp.bmp
        dest: setup/bearsampp.bmp
      - source: img/artwork/prerequisites.bmp
        dest: setup/prerequisites.bmp
    repos: |
      Bearsampp/prerequisites

  # labels syncing
  - files:
      - source: .github/workflows/create-labels.yml
        dest: .github/workflows/create-labels.yml
      - source: .github/labels.yml
        dest: .github/labels.yml
    repos: |
      Bearsampp/.teams


  # All COMMON items go here
  - files:
      - source: img/artwork/Bearsampp-with-text-stroked.svg
        dest: img/Bearsampp-logo.svg
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: .git-sync/modules/.github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .git-sync/modules/.github/FUNDING.yml
        dest: .github/FUNDING.yml
      - source: .gitattributes
        dest: .gitattributes
    repos: |
        Bearsampp/dev
        Bearsampp/login-servers-enhanced
        Bearsampp/module-adminer
        Bearsampp/module-apache
        Bearsampp/module-composer
        Bearsampp/module-consolez
        Bearsampp/module-filezilla
        Bearsampp/module-ghostscript
        Bearsampp/module-git
        Bearsampp/module-gitlist
        Bearsampp/module-mailhog
        Bearsampp/module-mariadb
        Bearsampp/module-memcached
        Bearsampp/module-mysql
        Bearsampp/module-ngrok
        Bearsampp/module-nodejs
        Bearsampp/module-perl
        Bearsampp/module-phpmemadmin
        Bearsampp/module-phpmyadmin
        Bearsampp/module-phppgadmin
        Bearsampp/module-postgresql
        Bearsampp/module-python
        Bearsampp/module-ruby
        Bearsampp/module-svn
        Bearsampp/module-webgrind
        Bearsampp/module-websvn
        Bearsampp/module-xdc
        Bearsampp/module-yarn
        Bearsampp/modules-untouched
        Bearsampp/prerequisites
        Bearsampp/.teams
