# File controlling which repos get what files.  See: https://github.com/BetaHuhn/repo-file-sync-action
group:

  # Test tebsite
  - files:
      - source: ".git-sync/site/.github"
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
    repos: |
      Bearsampp/website@main
      Bearsampp/Bearsampp.github.io@main

  # second group - Normal modules
  - files:
      - source: .git-sync/modules/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
    repos: |
      Bearsampp/module-apache@main
      Bearsampp/module-adminer@main
