group:
  - files:
      - source: .git-sync/site/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editor.config
        dest: .editor.config
      - source: img
        dest: img
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io
  - files:
      - source: .git-sync/modules/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editor.config
        dest: .editor.config
      - source: img
        dest: img
    repos: |
      Bearsampp/module-apache
      Bearsampp/module-adminer
