group:
  - files:
      - source: .git-sync/site/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io
  - files:
      - source: .git-sync/modules/.github
        dest: .github
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
        deleteOrphaned: true

      - source: .gitignore
        dest: .gitignore
        deleteOrphaned: true

      - source: .editorconfig
        dest: .editorconfig
        deleteOrphaned: true

      - source: img
        dest: img
        deleteOrphaned: true

    repos: |
      Bearsampp/module-apache
      Bearsampp/module-adminer

