group:

# Add modules since they share common needs
  - files:
      - source: .git-sync/modules/.github
        dest: .github
        deleteOrphaned: true # Removes deleted files
      - source: .github/CODEOWNERS
      - source: .github/dependabot.yml
      - source: .github/FUNDING.yml
      - LICENSE
      - .gitignore
      - .editorconfig
      - source: img/Bearsampp-logo.png
      - source: img/Bearsampp-32x32.png
        deleteOrphaned: true
    repos: |
      Bearsampp/Bearsampp
      Bearsampp/module-apache
      Bearsampp/module-adminer
      Bearsampp/module-filezilla
      Bearsampp/module-composer
      Bearsampp/dev
