name: Quickpick Dispatcher

on:
    pull_request:
        types:
            - closed
        branches:
            - 'main'
    workflow_dispatch:

jobs:
    if_merged:
        if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Invoke workflow in another repo with inputs
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.GH_PAT }}
                  repository: Bearsampp/Bearsampp
                  event-type: run-combine-releases
                  client-payload: '{"workflow": "combine_releases.yml"}'
