name: File sync

on:
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
   #   - name: Checkout
    #    uses: actions/checkout@v2

  - name: Checkout Repository
      uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
