name: File sync

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '.git-sync/site'
          user_name: 'Bearsampp'
          user_email: 'programming@hallhome.us'
          destination_repo: 'Bearsampp/website'
          destination_folder: '/'
          destination_branch: 'main'
