name: Label sponsors
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  build:
    name: Sponsor Labels
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/is-sponsor-label-action@v2.0.0
        with:
          label: Sponsor 💖
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
