name: Save repolist
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      - name: Repo-List-Generator
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1
      - name: Echo output
        run: echo ${{steps.repo.outputs.repoList}} > list.txt
      - name: pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=index.html
            list.txt
      - name: Commit
      uses: GuillaumeFalourd/git-commit-push@v1
        with:
          files: index.html
