name: Save repolist
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      # Create raw list of ALL repos in comma delimited format
      - name: Repo-List-Generator
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1

      # For some dumb reason we need to physically save the file.
      - name: To File
        uses: GuillaumeFalourd/command-output-file-action@v1
        with:
          command_line: echo ${{steps.repo.outputs.repoList}}
          output_file_name: current-repos.md

      # Now that its saved we can use an action to replace .settings since we don't want that one in the list.
      - name: Find-and-replace settings
        uses: mad9000/actions-find-and-replace-string@2
        id: findandreplace
        with:
          source: ${{steps.repo.outputs.repoList}}
          find: ".settings,"
          replace: ''

      # Now we need to save the file again because jacobtomlinson/gha-find-replace@v2 won't work properly otherwise.
      - name: To File - mad9000
        uses: GuillaumeFalourd/command-output-file-action@v1
        with:
          command_line: echo ${{ steps.findandreplace.outputs.value }}
          output_file_name: current-repos.md

      # Now that its saved replace , with eol
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        id: gha
        with:
          find: ","
          replace: "\n"
          include: current-repos.md

      # Now that everything is done lets actually physically create the file.
      - uses: GuillaumeFalourd/git-commit-push@v1
        with:
          files: current-repos.md
