name: Save repolist
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      - name: Repo-List-Generator
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1
      - name: To File
        uses: GuillaumeFalourd/command-output-file-action@v1
        with:
          command_line: echo ${{steps.repo.outputs.repoList}}
          output_file_name: current-repos.md
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
            find: ","
            replace: "\n"
            include: "current-repos.md"
      - name: Remove .settings
        uses: jacobtomlinson/gha-find-replace@v2
        with:
           find: ^\.settings$
           replace: ""
           regex: true
           include: "current-repos.md"
      - uses: GuillaumeFalourd/git-commit-push@v1
        with:
          files: current-repos.md
