name: Save repolist
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      - name: Repo-List-Generator
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1
      - name: To File
        uses: GuillaumeFalourd/command-output-file-action@v1
        with:
          command_line: echo ${{steps.repo.outputs.repoList}}
          output_file_name: output.txt
