name: Save repolist
on: [ push ]
jobs:
  Repo-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      # Create raw list of ALL repos in comma delimited format
      - name: Repo-List-Generator
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1

      # Now that its saved we can use an action to replace .settings since we don't want that one in the list.
      - name: Find-and-replace settings
        uses: mad9000/actions-find-and-replace-string@2
        id: settings
        with:
          source: ${{steps.repo.outputs.repoList}}
          find: ".settings,"
          replace: ''

      # Now remove fixed repos
      - name: Remove pages
        uses: mad9000/actions-find-and-replace-string@2
        id: pages
        with:
          source: ${{ steps.settings.outputs.value }}
          find: "bearsampp.github.io,"
          replace: ''

      # Now remove fixed repos
      - name: Remove website
        uses: mad9000/actions-find-and-replace-string@2
        id: website
        with:
          source: ${{ steps.pages.outputs.value }}
          find: "website,"
          replace: ''

      # Now that its saved replace , with eol
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        id: gha
        with:
          find: ","
          replace: "\nBearsampp/"
          include: ${{ steps.website.outputs.value }}

      - name: Get the final output
        run: echo "The replaced value is ${{ steps.gha.outputs.value }}"

      # Now that everything is done lets actually physically create the file.
      - uses: GuillaumeFalourd/git-commit-push@main
        with:
          files: current-repos.md
