Name: Repo list
on:
push:
  branches:
    - main
  workflow_dispatch:
  jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@master

  - name: Repo-List-Generator
    uses: yi-Xu-0100/repo-list-generator@v1.0.1
    with:
      my_token: ${{ secrets.GITHUB_TOKEN }}
  - name: Echo Output
      run: |
        echo repoList: ${{steps.repo.outputs.repoList}}
