name: Create labels

on:
  push:
    branches:
      - 'main'  # Don't change this. On the 'pages' source is in dev branch and auto-created & published in main/master
    paths:
      - '.github/labels.yml'
      - '.github/workflows/create-labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3.1.1
